/** Cột bảng `public.products` (file Kiot / kiotnew.csv) — dùng chung bootstrap CSV và đồng bộ từ POS. */
export const KIOTNEW_PRODUCT_DB_COLUMNS = [
  'ma_hang',
  'ma_vach',
  'ten_hang',
  'thuong_hieu',
  'gia_ban',
  'gia_von',
  'ton_kho',
  'kh_dat',
  'du_kien_het_hang',
  'ton_nho_nhat',
  'ton_lon_nhat',
  'dvt',
  'ma_dvt_co_ban',
  'quy_doi',
  'thuoc_tinh',
  'ma_hh_lien_quan',
  'trong_luong',
  'dang_kinh_doanh',
  'duoc_ban_truc_tiep',
  'gia_si',
]
